### ISSUE TITLE
Provide a way to specify a different config path

### ISSUE THREAD

**Issue by 0risc** [SwissArmyWrench/johnnybgoode#4]
It would be helpful to have an environment variable or something else to allow me specify a different configuration path.

Context: I would like to create a Homebrew formula to install `johnnybgoode`. One of the requirements for that is a test. It would be easier to provide a thorough test if the brew test could create a config file in a different place that would not risk overwriting a user's real config file.

**Comment by SwissArmyWrench** [comment]
I actually was thinking about this the other day! Should be fairly simple to implement, so I'll include it in the update I was about to release this weekend.

**Comment by SwissArmyWrench** [comment]
Implemented and released in the 1.2.0 that went up just now. `JOHNNYBGOODE_CONFIG_PATH` is the variable to use. Good luck with getting this set up with Homebrew! I'm not an apple user so I don't know how to do any of that.
